version: '3.8'
services:
  nebula:
    image: oshadmon/nebula
    container_name: nebula
    restart: unless-stopped
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - nebula_configs.env
    volumes:
      - /var/bin/nebula/configs:/app/nebula/configs
    healthcheck:
      test: [ "CMD-SHELL", "pgrep nebula && ip link show nebula1 | grep 'state UP'" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s