version: '3.8'
services:
  nebula:
    image: oshadmon/nebula
    container_name: nebula
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - nebula_configs.env
    volumes:
      - /var/bin/nebula/configs:/app/nebula/configs